### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=joshua&password=1234

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
#Cookie: SESSION=15b41d4c-409b-4fef-89b3-b345a3551dbc
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjkxOTMzMzgzfQ.MsTnb4OQDe3LCJqnt2T--4gz7DV6HZbeZ8-16wl_RGE